### ISSUE TITLE
Update on the project

### ISSUE THREAD

**Issue by mthurmond** [JuanJakobo/Pocketbook-Texteditor#1]
This is a really cool project and I saw the fork from the Kobo reader version. Did you ever get this working? I'm planning to install the firmware on my Kobo and then may look into (hopefully) simpler bluetooth e-reader options like the pocketbook.

**Comment by JuanJakobo** [comment]
Hi,
Yes it works. I use it daily. Since the latest PB version you can even pair your keyboard from within the PB Bluetooth menu. The only bad part is that you need to root your device as otherwise /dev/input cannot be created because the "normal" user lacks permissions. The root process however is quite easy.

**Comment by mthurmond** [comment]
Really helpful, thanks @JuanJakobo, and thanks for creating this.
